### ISSUE TITLE
Helpers `asHTML` duplicate words in richtext with styling (em, strong, ...)

### ISSUE THREAD

**Issue by MKlblangenois** [prismicio/prismic-client#198]
I'm trying to add bold on word with italic on some letter of this word.

On API, start and end chars are in good position for each styling, but helpers `asHTML` duplicate the part of word inside `<em>`

**Editor :** 
<img width="1170" alt="Capture d’écran 2021-11-26 à 14 10 45" src="https://user-images.githubusercontent.com/42929225/143587757-59703b51-1550-4bd9-ab66-47ecf3aec0c2.png">

**Render :**
<img width="809" alt="Capture d’écran 2021-11-26 à 14 11 40" src="https://user-images.githubusercontent.com/42929225/143587822-0cde6a19-1f3d-4e49-8996-ebd4eb8457ea.png">

I'm using helpers via Eleventy Shortcodes with [eleventy-plugin-prismic](https://github.com/prismicio-community/eleventy-plugin-prismic) like this :  
```nunjucks
{% prismic_asHTML  block_title %}
```

## Version
```bash
@prismicio/client: "^5.1.0"
node: "v16.11.1"
```

**Comment by lihbr** [comment]
Hey there, thank you for the report!

This looks like a bug with the underlying @prismicio/richtext package we rewrote recently for optimization purposes.

@angeloashmore can you try having a look? (If not I'll investigate on Monday)

In the meantime if you're just using the flat `asHTML` shortcode with no serializer, I'm afraid you can't do much about it :/

Definitely critical so we'll fix that shortly!

**Comment by lihbr** [comment]
Hey there, letting you know I managed to reproduce the above issue, it is indeed an issue with the new `@prismicio/richtext`. Working on a fix!

**Comment by angeloashmore** [comment]
Hey @MKlblangenois, thanks to @lihbr's work, this is fixed in `@prismicio/richtext@v2.0.0-beta.2`.

You should be able to fix this in your project by running the following command:

```sh
npm update @prismicio/richtext
```

Thanks for reporting this!

**Comment by MKlblangenois** [comment]
Hey @lihbr and @angeloashmore !

Thank you for your quick reply !

However, I still have a slight problem with the formatting of the words.

Let me explain :

**Case 1** 
![Capture d’écran 2021-11-30 à 09 15 31](https://user-images.githubusercontent.com/42929225/144010121-233568f6-bd3c-48c1-9d86-4ddd0a0c60ea.png)

```html
<!-- Excepted result -->
Some of our recent <strong><em>aaachi</em>evment</strong>

<!-- Actual result (https://ibb.co/7zw9Zgw) -->
Some of our recent <em>aaachi</em><strong><em>aaachi</em>evment</strong>
```

**Case 2**
![Capture d’écran 2021-11-30 à 09 19 37](https://user-images.githubusercontent.com/42929225/144010653-3d22fac1-c6a1-4653-bb20-7f40b7501ca9.png)

```html
<!-- Result -->
Some of our <strong>re<em>ce</em>nt</strong> <strong><em>aaachi</em>evment</strong>
```

As you can see, if I've only one word in strong with italic, the result are different than excepted, but with two occurence of bold with italic words in the same phrase, the result are good.

I have version `2.0.0-beta.2` installed

(Maybe you want I create a new issue ?)

### My configuration :

**My text** 
Some of our recent aaachievment

**Spans positions** 
```
[
  { start: 19, end: 25, type: 'em' },
  { start: 19, end: 31, type: 'strong' }
]
```

Thanks for your time !

**Comment by lihbr** [comment]
![image](https://user-images.githubusercontent.com/25330882/144014008-e0a3e305-0bd8-4c31-a45d-d45fe5a973b7.png)

**Comment by lihbr** [comment]
OK, performed some tests on 11ty and wasn't able to reproduce both of the above this time 🤔

![image](https://user-images.githubusercontent.com/25330882/144017021-da0282e2-5714-4abd-b412-439411a1ca2f.png)

I released an update to the 11ty plugin maintaining dependencies just in case.

If that fixed it for you, I'm still really interested in the result of your `npm ls @prismicio/richtext` result and your rich text field full content ☺️

**Comment by MKlblangenois** [comment]
Hey @lihbr !

Thanks for your update ! 

I was writing my answer when you release `eleventy-plugin-prismic@0.1.4` 😅

The plugin update solved the problem with a little manipulation:
1. Remove `@prismicio/client` from `node_modules`
2. Re-install `@prismicio/client` with `yarn add @prismicio/client@latest`
3. Install manually beta of `richtext` with `yarn add @prismicio/richtext@beta2.0.0-beta.2`

### The information you want
- **rich text data**
```bash
[
   {
      type: 'heading2',
      text: 'Some of our recent aaachievment',
      spans: [
         {
            start: 19,
            end: 25,
            type: 'em'
         },
         {
            start: 19,
            end: 31,
            type: 'strong'
         }
      ]
   }
]
```

- **log of `npm ls` before reinstall `@prismicio/client`**
```bash
├── @prismicio/richtext@2.0.0-beta.2
├─┬ eleventy-plugin-prismic@0.1.0
│ ├─┬ @prismicio/client@6.0.0-alpha.15 invalid
│ │ └─┬ @prismicio/helpers@2.0.0-beta.5
│ │   └── @prismicio/richtext@2.0.0-beta.2
│ └─┬ @prismicio/helpers@2.0.0-alpha.5 invalid
│   └── @prismicio/richtext@2.0.0-alpha.6
└─┬ prismic-dom@2.2.6
  └── @prismicio/richtext@1.1.0
```

- **log of `npm ls` after reinstall `@prismicio/client`**
```bash
├── @prismicio/richtext@2.0.0-beta.2
├─┬ eleventy-plugin-prismic@0.1.4
│ └─┬ @prismicio/helpers@2.0.0-beta.5
│   └── @prismicio/richtext@2.0.0-beta.2 deduped
└─┬ prismic-dom@2.2.6
  └── @prismicio/richtext@1.1.0
```

Thanks for your help and your time ! 😊

**Comment by lihbr** [comment]
Awesome! Weird one but issue fixed!

Just a side note, I see you're using `prismic-dom`, feel free to update it to the new `@prismicio/helpers` if you want ☺️

It is documented here: https://prismic.io/docs/technical-reference/prismicio-helpers, update should be fairly straightforward (but no pressure!), same for `@prismicio/client`, if you're using it alongside the plugin: https://prismic.io/docs/technical-reference/prismicio-client?version=v6

Cheers!
